export const advancedLearningEngineConfig = {
    experienceBufferMaxSize: 1000,
    significantExperienceAccuracyThreshold: 0.2,
    failureAnalysisAccuracyThreshold: 0.3,
    reinforcementAccuracyThreshold: 0.8,
    learningRate: 0.1,
    failurePenaltyMultiplier: 2,
    premiseAdjustmentDecay: 0.8,
    maxPremiseAdjustmentDepth: 5,
    ruleProductivityMinAttempts: 20,
    ruleDisableEffectivenessThreshold: 0.1,
    ruleEnableEffectivenessThreshold: 0.4,
    patternMinInstances: 50,
    patternSuccessRateThreshold: 0.8,
    conceptFormationMinInstances: 10,
    conceptConfidenceGrowthFactor: 20,
    shortcutConfidence: 0.9,
    shortcutPriority: 0.9,
    shortcutDurability: 0.9,
    shortcutQuality: 0.9,
    actionConsequenceConfidence: 0.7,
    actionConsequencePriority: 0.7,
    actionConsequenceDurability: 0.8,
    actionConsequenceQuality: 0.8,
    maintenanceInterval: 100,
    experienceBufferPruneSize: 250,
};
